version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
    zookeeper:
        image: "confluentinc/cp-zookeeper:5.2.1"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SYNC_LIMIT: 2
    keymanager-grpc:
        image: "ioannism/keymanager-grpc"
        ports:
            - 50051:50051
        restart: always
        environment:
            DB_URL: jdbc:postgresql://postgres:5432/pix
            DB_USER: keycloak
            DB_PASS: password
            ERP_URL: http://erp-itau:9091
            BCB_URL: http://bcb:8082
    postgres:
        image: 'postgres:alpine'
        volumes:
          - postgres-volume:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: password
          POSTGRES_DB: keycloak
          POSTGRES_HOST: postgres
    keycloak:
        image: jboss/keycloak
        ports:
          - 18443:8443
          - 18080:8080
          - 19990:9990
        depends_on:
          # Just a delay to wait for postgres! This is not recommended!
          - grafana
          - prometheus
          - jaeger
          - kafka
          - zookeeper
          - contas
          - analise
          - transacoes
          - postgres
        environment:
          DB_VENDOR: postgres
          DB_ADDR: postgres
          DB_PORT: 5432
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_PASSWORD: password
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: Pa55w0rd
          POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
    prometheus:
        image: prom/prometheus
        volumes:
         - prometheus-volume:/etc/prometheus/
        ports:
          - "9090:9090"
    jaeger:
        image: jaegertracing/all-in-one
        ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 14250:14250
          - 9411:9411
        environment:
          COLLECTOR_ZIPKIN_HTTP_PORT: 9411
volumes:
    prometheus-volume:
    postgres-volume: