micronaut:
  application:
    name: keymanagerRest
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: "/swagger/**"
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: "/swagger-ui/**"
grpc:
  channels:
    keymanager:
      address: '${KEYMANAGER_SERVER:`localhost:50051`}'
      plaintext: true
      max-retry-attempts: 10
endpoints:
  health:
    enabled: true

swagger-ui:
  enabled: true