apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-configmap
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  KEYMANAGER_SERVER: {{ .Values.KEYMANAGER_SERVER }}