apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus-deployment
spec:
    selector:
        matchLabels:
            app: prometheus
    template:
        metadata:
            name: prometheus-container
            labels:
                app: prometheus
        spec:
            containers:
                - name: prometheus-container
                image: prom/prometheus
                ports:
                    - containerPort: 9090