# SERVICE
apiVersion: v1
kind: Service
metadata:
    name: keymanager-grpc-service
spec:
    type: ClusterIP
    ports:
        - port: 50051
    selector:
        app: keymanager-grpc
---
# SECRET
apiVersion: v1
kind: Secret
metadata:
    name: keymanager-grpc-secret
type: Opaque
stringData:
    DB_USER: "keymanager"
    DB_PASSWORD: "123456"
---
# ENVIRONMENT
apiVersion: v1
kind: ConfigMap
metadata:
    name: keymanager-grpc-configmap
data:
    DB_URI: "jdbc:postgresql://external-pix-services:5432/pix"
    ITAU_URL: "http://external-pix-services:9091"
    BCB_URL: "http://external-pix-services:8082"
    DB_DIALECT: "POSTGRES"
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
    name: keymanager-grpc-deployment
spec:
    selector:
        matchLabels:
            app: keymanager-grpc
    template:
        metadata:
            name: keymanager-grpc
            labels:
                app: keymanager-grpc
        spec:
            containers:
                - name: keymanager-grpc-container
                  image: ioannism/keymanager-grpc
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 50051
                  envFrom:
                    - configMapRef:
                        name: keymanager-grpc-configmap
                    - secretRef:
                        name: keymanager-grpc-secret