# SERVICE
apiVersion: v1
kind: Service
metadata:
    name: keymanager-db-service
spec:
    type: ClusterIP
    ports:
        - port: 5432
    selector:
        app: keymanager-db
---
# ENVIRONMENT
apiVersion: v1
kind: ConfigMap
metadata:
    name: keymanager-db-configmap
data:
    POSTGRES_USER: "keymanager"
    POSTGRES_PASSWORD: "123456"
    POSTGRES_DB: "pix"
    POSTGRES_HOST: "keymanager-db-service"
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
    name: keymanager-db
spec:
    selector:
        matchLabels:
            app: keymanager-db
    template:
        metadata:
            name: keymanager-db
            labels:
                app: keymanager-db
        spec:
            containers:
                - name: keymanager-db-container
                  image: postgres:alpine
                  ports:
                    - containerPort: 5432
                  envFrom:
                    - configMapRef:
                        name: keymanager-db-configmap